[package]
name = "alt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
flate2 = "1.1.2"
libc = "0.2.175"
serde = { version = "1.0.219", features = ["serde_derive"] }
tar = "0.4.44"
toml = "0.9.5"
xz2 = "0.1.7"
zip = { version = "4.4", default-features = false, features = ["deflate"] }


[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
